@startuml
hide empty description
[*] --> 新创建
新创建      -d->        可运行: 开始(被调度)
可运行      -r->        被阻塞:     请示锁
被阻塞      -l->        可运行:     得到锁
可运行      -r->        等待:       等待通知
等待        -l->        可运行:     得到通知
可运行      -d->        计时等待:    等待超时或通知
计时等待    -u->        可运行:      出现超时或通知
可运行      -d->        被终止: 方法运行exits
被终止      -d->        [*]
@enduml